Pull request for The next web clone
berhanu-tarekegn/the-next-web-clone pull request #1
Opened 2020-06-22 20:10 UTC by berhanu-tarekegn

**The next web clone**
- This is the first **PR** for the whole clone
- has done through 
**CSS** 
**HTML5**

2020-06-22 22:49 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-06-22 23:05 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @umairarshadbutt and @berhanu-tarekegn, great job with this project :+1: README is very professional. :100:  Let us get our project approved by addressing the comments below: :smile: 

- PR must be a project description. You can go back to the project requirements and you will find a suitable description of the project
- The description of the README could also be improved. You can think of the description, as what Microverse wants you to learn in building the project. And you will find it in the project requirements
- ``` Medium``` The TNW logo is not appearing on the leftmost part of the page
![md](https://user-images.githubusercontent.com/46388113/85340761-372e3e80-b4d6-11ea-8f5c-937802ffa36f.png)
- ``` Large ``` We are missing the TNW logo at the top left corner of the row
![tnw](https://user-images.githubusercontent.com/46388113/85341252-406bdb00-b4d7-11ea-9848-70fbadf804db.png)
- ``` Footer ``` We are missing TNW logo
![ttt](https://user-images.githubusercontent.com/46388113/85342238-9fcaea80-b4d9-11ea-991c-49aa554fa069.png)
- Let improve semantics by replacing all the articles with the <article> tags 
- Let us implement the DRY rule in our CSS file

**NB:** I realized 3 of you participated in the project. In that case, you could explain why it happened

Kindly implement these changes and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-06-22 23:05 UTC, addod19 commented on index.html
> +                </div>
Let us improve semantics by using ```<article>``` instead of ```<div>```. Each of the ```<div>``` should be ```<article>```

2020-06-22 23:05 UTC, addod19 commented on index.html
> +                <li class="latest-news fund">
Each of the ```<li>``` should be ```<article>``` so we can improve on HTML semantics

2020-06-22 23:14 UTC, umairarshadbutt commented on index.html
> +                <li class="latest-news fund">
The Original  live website is using listing for this section

2020-06-22 23:14 UTC, umairarshadbutt commented on index.html
> +                </div>
done

2020-06-22 23:31 UTC, HADDADSOHAIB requested changes
### Status: Change Required :recycle: 

### Hello everyone  :hand: 

### Good job, you did great job with the project :+1: 

### Unfortunately, there are still some changes to get the project approved:
- **You did not implement any changes required by the previous TSE, please go back and implement all of them**
- Fix the validators issues:
![Screenshot from 2020-06-23 00-26-44](https://user-images.githubusercontent.com/26064042/85344686-43bb9280-b4e8-11ea-901d-88a59580071c.png)
- You have the whole first section missing in your project:
original
![Screenshot from 2020-06-23 00-27-53](https://user-images.githubusercontent.com/26064042/85344744-78c7e500-b4e8-11ea-921c-878245d43974.png)
your project:

![Screenshot from 2020-06-23 00-29-21](https://user-images.githubusercontent.com/26064042/85344814-9bf29480-b4e8-11ea-89e4-9d9a5b755305.png)

Please add it.
- Don't forget to provide an explanation for 3 person working on the same project.

### Once done with the changes, please ask for another code review.

2020-06-22 23:40 UTC, umairarshadbutt commented
- After Refreshing page, you got this section
- My partner Used two git accounts due to his using two accounts we are three at the project including me.

2020-06-22 23:52 UTC, christianotieno commented
## Pull Request under review by Christian Otieno (TSE)

2020-06-23 00:27 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning:
Hey Team :wave:
-
Good job with the changes! :tada: We are almost there.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
- For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.

### Main Page

|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/berhanu-tarekegn/the-next-web-clone/develop/index.html)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/22345961/85346236-86d43080-b4fd-11ea-888b-85e830bc9637.png)|![clone](https://user-images.githubusercontent.com/22345961/85346241-8c317b00-b4fd-11ea-993e-4c780f13c18e.png)|

- Increase the height of the top three articles of your clone to match that of the source page.
- Add the TWN logo at the top left corner of the main article ([link to page](https://thenextweb.com/)).
##
### Latest News Section
|[Source Page](https://thenextweb.com/)|[Clone page](https://raw.githack.com/berhanu-tarekegn/the-next-web-clone/develop/index.html)|
|:---:|:---:|
|![latest-news](https://user-images.githubusercontent.com/22345961/85346516-622c8880-b4fe-11ea-952e-bfc70add8d7b.png)|![latest-news-clone](https://user-images.githubusercontent.com/22345961/85346523-6789d300-b4fe-11ea-8020-fc783aa7cf14.png)|

- This section should align only 4 articles per row ([link to page](https://thenextweb.com/)). Let's work on that.
- Make sure this and the latest funding section have properly been centred.
##
### Latest Funding Section

|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/berhanu-tarekegn/the-next-web-clone/develop/index.html)|
|:---:|:---:|
|![latest-funding](https://user-images.githubusercontent.com/22345961/85347022-fb0fd380-b4ff-11ea-8969-062bf810c719.png)|![latest-funding-clone](https://user-images.githubusercontent.com/22345961/85347025-006d1e00-b500-11ea-9df9-7f290568d010.png)|

- Centre this section.
##

### Categories (Apps, Gear, Tech, etc) section

|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/berhanu-tarekegn/the-next-web-clone/develop/index.html)|
|:---:|:---:|
|![app-gear](https://user-images.githubusercontent.com/22345961/85346816-4bd2fc80-b4ff-11ea-8759-85686ff1860f.png)|![app-gear-clone](https://user-images.githubusercontent.com/22345961/85346822-51304700-b4ff-11ea-9e54-2565d4d49f93.png)|

- It should align 3 category boxes per row ([link to page](https://thenextweb.com/))
##

### Latest Deals Section
|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/berhanu-tarekegn/the-next-web-clone/develop/index.html)|
|:---:|:---:|
|![latest-deals](https://user-images.githubusercontent.com/22345961/85347387-0d3e4180-b501-11ea-8753-01a6aef209c0.png)|![latest-deals-clone](https://user-images.githubusercontent.com/22345961/85347389-129b8c00-b501-11ea-9139-9e520f42fb42.png)|

- The latest deals should as well align four articles per row.
##

- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-23 08:57 UTC, trekab requested changes
## Changes Required! :recycle: 
Hi @team, I'd like to start by commending you for the effort you are putting in to meet this project's requirements. There are a few changes you need to make to complete. These are:

- [x] Please make your navigation links actual links and label them more appropriately. This will make your clone appear more like the original site.
- [x] Your navigation bar is broken on medium-size screens.
- [x] For medium and small screens, the TNW logo should disappear from the `Top 3 articles section`.
- [x] For the `Top 3 articles section` your largest article is missing its bottom text.

![Screenshot](https://github.com/trekab/images/blob/master/img/berhanu/responsive.png?raw=true)

- [ ] At 862px - 863px, your `Latest news`, `Latest funding`, and `Latest deals` sections seem to be responding incorrectly. Try to refine your break-points. Your CSS styles should use [media queries](https://www.w3schools.com/css/css_rwd_mediaqueries.asp) for 2 breakpoints ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/breakpoints_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/)). 
  - No small breakpoint as it is mobile-first and the base styles are for the mobile screen. ([Screenshot on mobile-first approach](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/mobile_first.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/))
  - medium: min-width around 768px
  - large: min-width 1024px

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-06-23 11:04 UTC, HADDADSOHAIB requested changes
### Status: Change Required :recycle: 

### Hi everyone   :hand: 

### Great project, godd work, you implemented a lot of required changes, but there is some changes to be made:
- Please, always make sure that you page is not messed up, the navigation bar need improvement:
your project:
![Screenshot from 2020-06-23 11-48-59](https://user-images.githubusercontent.com/26064042/85395529-359d5e80-b548-11ea-93b6-1343a6521861.png)
original:
![Screenshot from 2020-06-23 11-54-08](https://user-images.githubusercontent.com/26064042/85395579-48b02e80-b548-11ea-982a-76871d849e00.png)
- There is some overlapping text in small size:
![Screenshot from 2020-06-23 12-00-43](https://user-images.githubusercontent.com/26064042/85396230-47333600-b549-11ea-9718-6783513d53da.png)
![Screenshot from 2020-06-23 12-01-59](https://user-images.githubusercontent.com/26064042/85396289-603be700-b549-11ea-8a72-a0dc76e44913.png)
As rule of thumb that you need to follow is that your final product need to be looking good, nothing messed up, so before you submit again for code review, check your project using the developer tool, check different screen size and fix any issue.

### Once done with the changes, ask for another code review.

2020-06-23 12:31 UTC, trekab requested changes
## Changes Required! :recycle: 
Hi @team, much as you have endeavored to work on some of the previous feedback from the TSEs, it appears that you have neglected some other important feedback. Please note that we are here to help you learn and I encourage you to reach out to any of the TSEs if you feel that the feedback given is unclear. On that note, among other things, I still find a problem with the responsiveness of your clone. Given that the goal of this project is to help us appreciate and master working with responsive design, I'd like to point out the following:
- [ ] At the __same__ point that the TNW logo disappears from the `Top 3 articles section`, the `latest news section`, `Latest Funding section`, and the `Latest deals sections` align 3 articles per row while the `Categories (Apps, Gear, Tech, etc) section` aligns 2 category boxes per row ([link to page](https://thenextweb.com/)). Your clone behaves differently from this. I suggest that you look at my last feedback about break-points. This seems like an easier route for you to fix this issue.

__Kindly make the necessary changes and submit another code review request.__
_Again, feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-06-23 15:18 UTC, andresporras3423 commented
### **Pull Request Under Review By Oscar Russi (TSE)**

2020-06-23 16:56 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @umairarshadbutt @BerhanuTarekegn** 
Good job with your  progress on this project :muscle:  
There are still some improvements to do before you can go ahead:
- your page should show the TNW logo when big screen size:

![](https://i.imgur.com/laArpvml.png)

- In medium-size screen you page look like this, check the original page for the same size:

![](https://i.imgur.com/VMT3cxEl.png)

- For small screen size let compare your page and the original. Yours:

![](https://i.imgur.com/L3m1SEXl.png)

and the source page:

![](https://i.imgur.com/JtDw3Bbl.png)

Besides you page still has some other issues:
- Latest news section should be two columns in medium-size screens
- lastest funding should  be two columns in medium size screen
- latest deals section should be three columns in medium size screen
- check how the footer changes in the original page in small screen size

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-06-23 17:40 UTC, tirthajyoti-ghosh approved these changes
# Status: Approved ✔

## You have done all the changes requested by the previous reviewers. 

### However, I highly recommend that you take note of these [OPTIONAL] changes below.

#### [OPTIONAL]
- Add the red gradient background to the top article sections.
- Take note of this ->
![Annotation 2020-06-23 230635](https://user-images.githubusercontent.com/57726348/85436231-50062500-b5a6-11ea-81d9-8830894eb7c7.jpg)
There shouldn't be any extra space.

Original
![image](https://user-images.githubusercontent.com/57726348/85436342-86dc3b00-b5a6-11ea-8e99-c66efa546ab8.png)

Consider applying these changes before merging.

Happy coding 👨‍💻

2020-06-24 09:14 UTC, merged